// Motion RP V9: background-only YouTube audio, minimal controls, auto-next through 27 tracks.
const TRACKS = [
  { id: '0ftgAyfFUMc', title: 'TRACK 01' }, { id: 'vyxSJr_CC60', title: 'TRACK 02' }, { id: 'kQnDpRtRrEc', title: 'TRACK 03' },
  { id: 'NweMRU8uNko', title: 'TRACK 04' }, { id: 'tgA-wVkuZGo', title: 'TRACK 05' }, { id: 'Ty-CHgmCeKw', title: 'TRACK 06' },
  { id: 'CnT6NRiTz9M', title: 'TRACK 07' }, { id: 'OFlilpsRuMg', title: 'TRACK 08' }, { id: 'g0v7Ow6Epog', title: 'TRACK 09' },
  { id: 'YpxzPXaYyM4', title: 'TRACK 10' }, { id: 'vMxOz_6gWOE', title: 'TRACK 11' }, { id: 'tBKYI3-3lMg', title: 'TRACK 12' },
  { id: '5IqLJA8unvA', title: 'TRACK 13' }, { id: 'CFmikQCo_h4', title: 'TRACK 14' }, { id: 'Us9BEYzqbXU', title: 'TRACK 15' },
  { id: 'LSik3Jdnhkw', title: 'TRACK 16' }, { id: 'lbWLy08udII', title: 'TRACK 17' }, { id: 'k-UABoxsk5w', title: 'TRACK 18' },
  { id: 'QinT9kMh4Sc', title: 'TRACK 19' }, { id: 'cExgrHIfHUA', title: 'TRACK 20' }, { id: '117XLL2S-Mk', title: 'TRACK 21' },
  { id: '85d_mgHjt58', title: 'TRACK 22' }, { id: 'D49adOjVNcs', title: 'TRACK 23' }, { id: 'oro2A3UwlmA', title: 'TRACK 24' },
  { id: 'YYEETzzqFiM', title: 'TRACK 25' }, { id: 'b0Zm3DOoJn8', title: 'TRACK 26' }, { id: 'lehtwEA9IU4', title: 'TRACK 27' }
];
let currentIndex=0, player=null, playerReady=false, muted=true, playing=false, lastProgress=0, fallback=0;
const playBtn=document.getElementById('playBtn'), muteBtn=document.getElementById('muteBtn'), prevBtn=document.getElementById('prevBtn'), nextBtn=document.getElementById('nextBtn'), volume=document.getElementById('volume'), volText=document.getElementById('volText'), status=document.getElementById('status'), bar=document.getElementById('barFill'), percent=document.getElementById('percent'), steps=[document.getElementById('s1'),document.getElementById('s2'),document.getElementById('s3'),document.getElementById('s4')];
function loadTrack(index,autoPlay=true){currentIndex=(index+TRACKS.length)%TRACKS.length;status.textContent=`MOTION CITY • ${TRACKS[currentIndex].title}`;if(!playerReady||!player)return;try{player.loadVideoById({videoId:TRACKS[currentIndex].id,startSeconds:0});if(autoPlay){player.mute();muted=true;player.setVolume(Number(volume.value));player.playVideo();playing=true}}catch(e){fallbackIframe(TRACKS[currentIndex].id)}}
function fallbackIframe(id){const host=document.getElementById('youtubePlayer');host.innerHTML=`<iframe width="2" height="2" src="https://www.youtube.com/embed/${id}?autoplay=1&mute=1&playsinline=1&enablejsapi=1&rel=0&controls=0&origin=https%3A%2F%2Fallrealprof976-ai.github.io" frameborder="0" allow="autoplay; encrypted-media" referrerpolicy="strict-origin-when-cross-origin"></iframe>`}
window.onYouTubeIframeAPIReady=function(){player=new YT.Player('youtubePlayer',{width:'2',height:'2',videoId:TRACKS[0].id,playerVars:{autoplay:1,controls:0,disablekb:1,playsinline:1,rel:0,modestbranding:1,iv_load_policy:3,origin:'https://allrealprof976-ai.github.io'},events:{onReady:e=>{playerReady=true;e.target.mute();e.target.setVolume(Number(volume.value));e.target.playVideo();muted=true;playing=true;status.textContent='MOTION CITY • TRACK 01'},onStateChange:e=>{if(e.data===YT.PlayerState.ENDED)loadTrack(currentIndex+1,true);else if(e.data===YT.PlayerState.PLAYING)playing=true;else if(e.data===YT.PlayerState.PAUSED)playing=false;updateButtons()},onError:()=>{status.textContent='MUSIC SKIPPED • MOVING TO NEXT';setTimeout(()=>loadTrack(currentIndex+1,true),700)}}})};
function updateButtons(){playBtn.textContent=playing?'Ⅱ':'▶';muteBtn.textContent=muted?'🔇':'🔊'}
playBtn.addEventListener('click',()=>{if(!playerReady||!player)return;if(playing)player.pauseVideo();else player.playVideo();playing=!playing;updateButtons()});
muteBtn.addEventListener('click',()=>{if(!playerReady||!player)return;if(muted){player.unMute();player.setVolume(Number(volume.value));muted=false}else{player.mute();muted=true}updateButtons()});
volume.addEventListener('input',()=>{const v=Number(volume.value);volText.textContent=`${v}%`;if(playerReady&&player){player.setVolume(v);if(v===0){player.mute();muted=true}else if(!muted)player.unMute()}updateButtons()});
prevBtn.addEventListener('click',()=>loadTrack(currentIndex-1,true));nextBtn.addEventListener('click',()=>loadTrack(currentIndex+1,true));
function setProgress(v){v=Math.max(0,Math.min(100,Math.round(v)));lastProgress=v;bar.style.width=v+'%';percent.textContent=v+'%';const thresholds=[0,25,55,80],labels=['INITIALIZING','LOADING ASSETS','STARTING SCRIPTS','ENTERING MOTION CITY'];steps.forEach((s,i)=>{s.classList.remove('active','done');if(v>=thresholds[i]+25&&i<3){s.classList.add('done');s.textContent='✓ '+labels[i]}else if(v>=thresholds[i]){s.classList.add('active');s.textContent='◉ '+labels[i]}else{s.textContent='○ '+labels[i]}})}
window.addEventListener('message',e=>{if(e.data?.eventName==='loadProgress'){const v=(e.data.loadFraction||0)*100;fallback=v;setProgress(v)}});
setInterval(()=>{if(lastProgress<100){fallback=Math.min(96,Math.max(fallback,lastProgress)+.8+Math.random()*1.8);setProgress(fallback)}},500);updateButtons();
const api=document.createElement('script');api.src='https://www.youtube.com/iframe_api';document.head.appendChild(api);
